# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from about_us import Ui_AboutUS
from simpson_13 import Ui_simpson_13

class Ui_MainWindow(object):

    def open_about_us(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AboutUS()
        self.ui.setupUi(self.window)
        self.window.show()

    def open_simpson_13(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_simpson_13()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(607, 533)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(240, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_2.setFont(font)
        self.btn_2.setObjectName("btn_2")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(240, 320, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_6.setFont(font)
        self.btn_6.setObjectName("btn_6")
        self.about_us_btn = QtWidgets.QPushButton(self.centralwidget, clicked = self.open_about_us)
        self.about_us_btn.setGeometry(QtCore.QRect(430, 480, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.about_us_btn.setFont(font)
        self.about_us_btn.setObjectName("about_us_btn")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget, clicked = self.open_simpson_13)
        self.btn_0.setGeometry(QtCore.QRect(240, 80, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_0.setFont(font)
        self.btn_0.setObjectName("btn_0")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(240, 240, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_4.setFont(font)
        self.btn_4.setObjectName("btn_4")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(240, 280, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_5.setFont(font)
        self.btn_5.setObjectName("btn_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 30, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(240, 120, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_1.setFont(font)
        self.btn_1.setObjectName("btn_1")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(240, 360, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_7.setFont(font)
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(240, 400, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_8.setFont(font)
        self.btn_8.setObjectName("btn_8")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(240, 200, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_3.setFont(font)
        self.btn_3.setObjectName("btn_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_2.setText(_translate("MainWindow", "Trapecios"))
        self.btn_6.setText(_translate("MainWindow", "Punto Fijo"))
        self.about_us_btn.setText(_translate("MainWindow", "Acerca de nosotros"))
        self.btn_0.setText(_translate("MainWindow", "Simpson 1/3"))
        self.btn_4.setText(_translate("MainWindow", "Newton Raphson"))
        self.btn_5.setText(_translate("MainWindow", "Secante"))
        self.label.setText(_translate("MainWindow", "CALCULADORA DE METODOS NUMERICOS"))
        self.btn_1.setText(_translate("MainWindow", "Simpson 3/8"))
        self.btn_7.setText(_translate("MainWindow", "Tipos de errores"))
        self.btn_8.setText(_translate("MainWindow", "Falsa Posicion"))
        self.btn_3.setText(_translate("MainWindow", "Biseccion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
